# The Basics
dist: trusty
language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew build
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - '[[ "$TRAVIS_BRANCH" = "develop" ]] && ./gradlew uploadArchives'

# Ugh.
notifications:
  email: false
